// icons.js

ICONNAMES = [
  'oi oi-ban',
  'oi oi-bell',
  'oi oi-briefcase',
  'oi oi-bug',
  'oi oi-heart',
  'oi oi-camera-slr',
  'oi oi-cog',
  'oi oi-command',
  'oi oi-envelope-closed',
  'oi oi-headphones',
  'oi oi-image',
  'oi oi-key',
  'oi oi-lock-locked',
  'oi oi-map-marker',
  'oi oi-medical-cross',
  'oi oi-microphone',
  'oi oi-moon',
  'oi oi-musical-note',
  'oi oi-phone',
  'oi oi-rain',
  'oi oi-rss',
  'oi oi-sun',
  'oi oi-shield',
  'oi oi-tablet',
  'oi oi-target',
  'oi oi-trash',
  'oi oi-volume-high',
  'oi oi-wifi',
  'oi oi-wrench',
  'oi oi-x'
];